version: '2'
services:
    campfire-mongodb:
        image: mongo:4.0.2
        restart : always
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/CampFire/mongodb/:/data/db/


